"""Add credentials to device model

Revision ID: 91360e02c688
Revises: 
Create Date: 2025-07-04 18:56:45.912888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91360e02c688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Añadimos la columna 'encrypted_password', que puede ser nula.
    op.add_column('devices', sa.Column('encrypted_password', sa.Text(), nullable=True))
    
    # Añadimos la columna 'username', especificando un server_default.
    # Esto le dice a PostgreSQL que use 'admin' para las filas existentes
    # y como valor por defecto para futuras inserciones si no se especifica.
    op.add_column('devices', sa.Column('username', sa.String(), nullable=False, server_default='admin'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'encrypted_password')
    op.drop_column('devices', 'username')
    # ### end Alembic commands ###
