"""Add scan message to device

Revision ID: b5857dfbcee5
Revises: 42a501a60661
Create Date: 2025-07-07 16:01:01.489259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5857dfbcee5'
down_revision: Union[str, Sequence[str], None] = '42a501a60661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_scan_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_scan_message')
    # ### end Alembic commands ###
