"""initial schema (squashed v2.5)

Revision ID: 0c8945215fc4
Revises: 
Create Date: 2025-08-11 19:48:33.034883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8945215fc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('last_scan_status', sa.String(), nullable=True),
    sa.Column('last_scan_message', sa.Text(), nullable=True),
    sa.Column('last_scan_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('f5_device_hostname', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('partition', sa.String(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_cert_device_name')
    )
    op.create_index(op.f('ix_certificates_common_name'), 'certificates', ['common_name'], unique=False)
    op.create_index(op.f('ix_certificates_expiration_date'), 'certificates', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_certificates_f5_device_hostname'), 'certificates', ['f5_device_hostname'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_name'), 'certificates', ['name'], unique=False)
    op.create_table('renewal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_certificate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CSR_GENERATED', 'COMPLETED', 'FAILED', name='renewalstatus'), nullable=False),
    sa.Column('csr_content', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_requests_id'), 'renewal_requests', ['id'], unique=False)
    op.create_index(op.f('ix_renewal_requests_original_certificate_id'), 'renewal_requests', ['original_certificate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewal_requests_original_certificate_id'), table_name='renewal_requests')
    op.drop_index(op.f('ix_renewal_requests_id'), table_name='renewal_requests')
    op.drop_table('renewal_requests')
    op.drop_index(op.f('ix_certificates_name'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_f5_device_hostname'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_expiration_date'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_common_name'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
