"""Establish device-certificate relationship via ID

Revision ID: 42a501a60661
Revises: 91360e02c688
Create Date: 2025-07-05 20:02:55.108807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a501a60661'
down_revision: Union[str, Sequence[str], None] = '91360e02c688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificates', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_column('certificates', 'device_id')
    # ### end Alembic commands ###
