"""add_admin_panel_tables

Revision ID: 60980336045c
Revises: admin_hybrid_auth_v25
Create Date: 2025-09-22 20:39:01.092883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60980336045c'
down_revision: Union[str, Sequence[str], None] = 'admin_hybrid_auth_v25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.drop_index('ix_auth_providers_provider_type', table_name='auth_providers')
    op.drop_table('auth_providers')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.add_column('system_config', sa.Column('updated_by', sa.String(), nullable=True))
    op.drop_constraint('system_config_category_key_key', 'system_config', type_='unique')
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_unique_constraint('uq_config_category_key', 'system_config', ['category', 'key'])
    op.drop_column('system_config', 'last_modified_by')
    op.drop_column('system_config', 'validation_regex')
    op.drop_column('system_config', 'data_type')
    op.drop_column('system_config', 'created_by')
    op.drop_column('system_config', 'is_secret')
    op.drop_column('system_config', 'created_at')
    op.drop_column('system_config', 'default_value')
    op.drop_column('system_config', 'display_order')
    op.drop_column('system_config', 'is_readonly')
    op.alter_column('user_activities', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_activities', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user_activities', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_activities', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.drop_constraint('user_activities_user_id_fkey', 'user_activities', type_='foreignkey')
    op.create_foreign_key(None, 'user_activities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'auth_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'ad_groups',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'last_modified_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'last_modified_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'ad_groups',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'permissions',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'),
               existing_nullable=False)
    op.alter_column('users', 'auth_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'user_activities', type_='foreignkey')
    op.create_foreign_key('user_activities_user_id_fkey', 'user_activities', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.alter_column('user_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_activities', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_activities', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('user_activities', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user_activities', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('system_config', sa.Column('is_readonly', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('default_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('is_secret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('data_type', sa.VARCHAR(length=50), server_default=sa.text("'string'::character varying"), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('validation_regex', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('last_modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_config_category_key', 'system_config', type_='unique')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.create_unique_constraint('system_config_category_key_key', 'system_config', ['category', 'key'])
    op.drop_column('system_config', 'updated_by')
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_table('auth_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auth_providers_pkey'),
    sa.UniqueConstraint('name', name='auth_providers_name_key')
    )
    op.create_index('ix_auth_providers_provider_type', 'auth_providers', ['provider_type'], unique=False)
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
