"""add_discovery_tables

Revision ID: 78dd604e1e3d
Revises: ddea831f15f5
Create Date: 2025-12-05 20:39:02.812574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dd604e1e3d'
down_revision: Union[str, Sequence[str], None] = 'ddea831f15f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='discoveryjobstatus'), nullable=False),
    sa.Column('subnets', sa.Text(), nullable=False),
    sa.Column('credential_set', sa.String(), nullable=True),
    sa.Column('total_ips', sa.Integer(), nullable=True),
    sa.Column('scanned_ips', sa.Integer(), nullable=True),
    sa.Column('found_devices', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_jobs_id'), 'discovery_jobs', ['id'], unique=False)
    op.create_table('discovered_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('ha_state', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IMPORTED', 'SKIPPED', 'DUPLICATE', 'FAILED', name='discovereddevicestatus'), nullable=False),
    sa.Column('probe_success', sa.Boolean(), nullable=True),
    sa.Column('probe_message', sa.Text(), nullable=True),
    sa.Column('credential_source', sa.String(), nullable=True),
    sa.Column('suggested_site', sa.String(), nullable=True),
    sa.Column('suggested_cluster_key', sa.String(), nullable=True),
    sa.Column('imported_device_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_devices_id'), 'discovered_devices', ['id'], unique=False)
    op.create_index(op.f('ix_discovered_devices_job_id'), 'discovered_devices', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_devices_job_id'), table_name='discovered_devices')
    op.drop_index(op.f('ix_discovered_devices_id'), table_name='discovered_devices')
    op.drop_table('discovered_devices')
    op.drop_index(op.f('ix_discovery_jobs_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    # ### end Alembic commands ###
