"""Add profiles cache tables

Revision ID: f3d27fa723f1
Revises: 0c8945215fc4
Create Date: 2025-08-14 17:35:27.658768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d27fa723f1'
down_revision: Union[str, Sequence[str], None] = '0c8945215fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cert_profile_links_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('cert_name', sa.String(), nullable=False),
    sa.Column('profile_full_path', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'cert_name', 'profile_full_path', name='uq_cert_profile_per_device')
    )
    op.create_index(op.f('ix_cert_profile_links_cache_cert_name'), 'cert_profile_links_cache', ['cert_name'], unique=False)
    op.create_index(op.f('ix_cert_profile_links_cache_device_id'), 'cert_profile_links_cache', ['device_id'], unique=False)
    op.create_index(op.f('ix_cert_profile_links_cache_profile_full_path'), 'cert_profile_links_cache', ['profile_full_path'], unique=False)
    op.create_table('ssl_profile_vips_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('profile_full_path', sa.String(), nullable=False),
    sa.Column('vip_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'profile_full_path', 'vip_name', name='uq_profile_vip_per_device')
    )
    op.create_index(op.f('ix_ssl_profile_vips_cache_device_id'), 'ssl_profile_vips_cache', ['device_id'], unique=False)
    op.create_index(op.f('ix_ssl_profile_vips_cache_profile_full_path'), 'ssl_profile_vips_cache', ['profile_full_path'], unique=False)
    op.create_table('ssl_profiles_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('partition', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'partition', 'profile_name', name='uq_profiles_device_partition_name')
    )
    op.create_index(op.f('ix_ssl_profiles_cache_device_id'), 'ssl_profiles_cache', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssl_profiles_cache_device_id'), table_name='ssl_profiles_cache')
    op.drop_table('ssl_profiles_cache')
    op.drop_index(op.f('ix_ssl_profile_vips_cache_profile_full_path'), table_name='ssl_profile_vips_cache')
    op.drop_index(op.f('ix_ssl_profile_vips_cache_device_id'), table_name='ssl_profile_vips_cache')
    op.drop_table('ssl_profile_vips_cache')
    op.drop_index(op.f('ix_cert_profile_links_cache_profile_full_path'), table_name='cert_profile_links_cache')
    op.drop_index(op.f('ix_cert_profile_links_cache_device_id'), table_name='cert_profile_links_cache')
    op.drop_index(op.f('ix_cert_profile_links_cache_cert_name'), table_name='cert_profile_links_cache')
    op.drop_table('cert_profile_links_cache')
    # ### end Alembic commands ###
